version: '3.9'
services:
  run-dsp:
    build:
      context: .
    command: server
    environment:
      - LOGLEVEL=debug
      - SERVER.PROVIDER.ADDRESS=reference-provider:9090
      - SERVER.PROVIDER.INSECURE=true
      - SERVER.DSP.EXTERNALURL=http://127.0.0.1:8080/
      - SERVER.PERSISTENCE.BADGER.MEMORY=true
    ports:
      - '18080:8080'
    depends_on:
      - reference-provider
  reference-provider:
    image: ghcr.io/go-dataspace/reference-provider:main
    command: server
    environment:
      - LOGLEVEL=debug
      - PROVIDER_INSECURE=true
      - EXTERNAL_URL=http://127.0.0.1:19091/
    volumes:
    - .:/var/lib/run-dsp/fsprovider
    ports:
      - '19091:9091'
      - '19090:9090'
