### GLOBAL OPTIONS ###
debug = true       # Sets the output to a human readable format and sets the log level to debug. ($DEBUG)
logLevel = "debug" # Sets the log level. Valid values: debug/info/warn/error ($LOGLEVEL)

### SERVER OPTIONS ###
[server]

## Dataspace component configuration
[server.dsp]
address = "127.0.0.1"                 # IP address of the local machine to listen to for dataspace requests. ($SERVER.DSP.ADDRESS)
port = 8080                           # TCP port to listen on for dataspace requests. ($SERVER.DSP.PORT)
externalURL = "http://127.0.0.1:8080" # Address that we are reachable by to other dataspace participants. ($SERVER.DSP.EXTERNALURL)

## Provider gRPC settings
[server.provider]
address = "reference-provider:9090" # The address of the provider service. ($SERVER.PROVIDER.ADDRESS)
insecure = true                     # Disable TLS when connecting to the provider. ($SERVER.PROVIDER.INSECURE)

## Control service settings
[server.control]
enabled = true        # Enable the control service. ($SERVER.CONTROL.ENABLED)
address = "127.0.0.1" # IP address of the local machine to listen to for the control service. ($SERVER.CONTROL.ADDRESS)
port = 8081           # TCP port to listen on for the control service. ($SERVER.CONTROL.PORT)
insecure = true       # Disable TLS for the control service ($SERVER.CONTROL.INSECURE)

[client]
address = "127.0.0.1:8080" # Address to the RUN-DSP control service we want to connect to. ($CLIENT.ADDRESS)
insecure = true            # Disable TLS for the control service connection. ($CLIENT.INSECURE)
authMD = "Bearer abcde"    # What to put in the gRPC authorization metadata. ($CLIENT.AUTHMD)
