## This shows all configuration options of RUN-DSP, what they do and the corresponsing environment variables.###### RUN-DSP reference configuration file #####
## The default location of the configuration file is /etc/run-dsp/run-dsp.toml but you can change that
## with the `-c` command line flag

### GLOBAL OPTIONS ###
debug = true      # Sets the output to a human readable format and sets the log level to debug. ($DEBUG)
logLevel = "info" # Sets the log level. Valid values: debug/info/warn/error ($LOGLEVEL)

### SERVER OPTIONS ###
[server]

## Dataspace component configuration
[server.dsp]
address = "127.0.0.1"                 # IP address of the local machine to listen to for dataspace requests. ($SERVER.DSP.ADDRESS)
port = 8080                           # TCP port to listen on for dataspace requests. ($SERVER.DSP.PORT)
externalURL = "http://127.0.0.1:8080" # Address that we are reachable by to other dataspace participants. ($SERVER.DSP.EXTERNALURL)

## Provider gRPC settings
[server.provider]
address = "127.0.0.1:9090"            # The address of the provider service. ($SERVER.PROVIDER.ADDRESS)
insecure = false                      # Disable TLS when connecting to the provider. ($SERVER.PROVIDER.INSECURE)
caCert = "/path/to/ca.crt"            # Path to the CA certificate of the CA that issued the server certificate of the provider. ($SERVER.PROVIDER.CACERT)
clientCert = "/path/to/client.crt"    # Client certificate to authenticate with to the provider. ($SERVER.PROVIDER.CLIENTCERT)
clientCertKey = "/path/to/client.key" # Key to the above mentioned certificate. ($SERVER.PROVIDER.CLIENTCERTKEY)

## Control service settings
[server.control]
enabled = true                   # Enable the control service. ($SERVER.CONTROL.ENABLED)
address = "127.0.0.1"            # IP address of the local machine to listen to for the control service. ($SERVER.CONTROL.ADDRESS)
port = 8081                      # TCP port to listen on for the control service. ($SERVER.CONTROL.PORT)
insecure = false                 # Disable TLS for the control service ($SERVER.CONTROL.INSECURE)
cert = "/path/to/control.crt"    # TLS certificate to use for the control service ($SERVER.CONTROL.CERT)
certKey = "/path/to/control.key" # Key to the above mentioned certificate. ($SERVER.CONTROL.CERTKEY)
verifyClientCerts = true         # Only allow access to clients with a certificate issued by the CA defined below. ($SERVER.CONTROL.VERIFYCLIENTCERTS)
clientCACert = "/etc/hosts"      # Certificate of the CA that issues client certificates. ($SERVER.CONTROL.CLIENTCACERT)

[client]
address = "127.0.0.1:8080"            # Address to the RUN-DSP control service we want to connect to. ($CLIENT.ADDRESS)
insecure = false                      # Disable TLS for the control service connection. ($CLIENT.INSECURE)
caCert = "/path/to/ca.crt"            # Path to the CA certificate of the CA that issued the certificate of the control service. ($CLIENT.CACERT)
clientCert = "/path/to/client.crt"    # Client certificate to authenticate with to the control service. ($CLIENT.CLIENTCERT)
clientCertKey = "/path/to/client.key" # Key to the above mentioned certificate. ($CLIENT.CLIENTCERTKEY)
authMD = "Bearer abcde"               # What to put in the gRPC authorization metadata. ($CLIENT.AUTHMD)
